name: 'dbt_aws'
version: '1.0.0'

profile: 'dbt_example'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Variáveis globais do projeto
vars:
  ambiente: 'desenvolvimento'
  data_minima: '2023-01-01'
  schema_nome: 'desenvolvimento_schema'

# Configurações de Modelos (Corrigido para corresponder a 'dbt_aws')
models:
  dbt_aws:
    staging:
      +schema: staging
      +materialized: view
      +tags: ['staging']
    
    intermediate:
      +materialized: ephemeral
      +tags: ['intermediate']

    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts']

# Configurações de Seeds
seeds:
  dbt_aws:
    +schema: seeds
    +tags: ['seeds']
    
# Configurações de Snapshots
snapshots:
  dbt_aws:
    +schema: snapshots
    +tags: ['snapshots']